// Generated by scripts/build_catalog_v26.py. Edit scripts/catalog_v26_content.py.
(() => {
  const catalog = {
  "places": [
    {
      "useMode": "메뉴별 주문·결제",
      "accessSummary": "좌석·출입구 단차는 매장에 확인",
      "access": "휠체어·유모차 진입과 화장실 동선은 현장 확인이 필요합니다.",
      "unknown": "당일 대기·가격, 재료와 알레르기 대응, 휴식시간, 무단차 좌석",
      "checkLabel": "메뉴·운영 안내",
      "name": "체부동잔치집돼지갈비",
      "category": "식당 · 돼지갈비",
      "visitWhen": "양념갈비를 구워 함께 먹기",
      "cost": "메뉴별 결제 · 주문 단위 확인",
      "schedule": "10시 개점 안내 · 종료 재확인",
      "closure": "휴무·주문 마감 매장 확인",
      "description": "세종마을 음식문화거리의 양념갈비 식당입니다. 메밀국수 한 그릇과, 테이블에서 고기를 구워 나누는 식사를 비교해 보세요.",
      "address": "서울 종로구 자하문로1길 24",
      "visitTip": "이름이 비슷한 국수집과 구분해 주소를 확인하세요. 공식 관광 자료의 마감시간이 달라 늦은 방문은 전화 확인이 필요합니다.",
      "photoLabel": "식당 외관과 간판",
      "hours": "10시 개점 안내 · 종료 재확인. 휴무·주문 마감 매장 확인.",
      "id": "chebu",
      "region": "seochon",
      "phone": "02-722-3555",
      "englishName": "Chebudong Janchijip Dwaejigalbi",
      "source": "https://french.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=60424",
      "sourceLabel": "한국관광공사 장소 안내",
      "coords": [
        37.5765455686434,
        126.971052442422
      ],
      "locationSource": "한국관광공사 장소 좌표",
      "locationSourceUrl": "https://french.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=60424",
      "photoSource": "https://french.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=60424",
      "photoAuthor": "한국관광공사 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/chebu.jpg",
      "preview": "images/places/optimized/chebu-480.webp",
      "largePreview": "images/places/optimized/chebu-960.webp",
      "imageAlt": "체부동잔치집돼지갈비 · 식당 외관과 간판",
      "hoursSummary": "10시 개점 안내 · 종료 재확인 · 휴무·주문 마감 매장 확인",
      "checkUrl": "https://french.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=60424",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      }
    },
    {
      "useMode": "메뉴별 주문·결제",
      "accessSummary": "좌석·출입구 단차는 매장에 확인",
      "access": "휠체어·유모차 진입과 화장실 동선은 현장 확인이 필요합니다.",
      "unknown": "당일 대기·가격, 재료와 알레르기 대응, 휴식시간, 무단차 좌석",
      "checkLabel": "메뉴·운영 안내",
      "name": "잘빠진메밀 서촌",
      "category": "식당 · 메밀국수",
      "visitWhen": "메밀국수와 수육으로 식사하기",
      "cost": "메뉴별 결제 · 현재 가격 확인",
      "schedule": "월–토 11–21:30 · 일 21시 종료",
      "closure": "휴식시간·주문 마감 별도 확인",
      "description": "메밀국수와 수육 등을 내는 서촌 본점입니다. 양념을 비비거나 국물과 먹는 면 요리를 고를 수 있습니다.",
      "address": "서울 종로구 자하문로 41-1",
      "visitTip": "관광공사 한글 주소와 영문 주소가 다릅니다. 서촌 본점의 최신 입구를 매장에 확인하세요. 메밀면도 육수·양념의 채식·알레르기 대응은 별도 확인입니다.",
      "photoLabel": "공식 안내의 매장 외관 · 현재 입구 확인",
      "hours": "월–토 11–21:30 · 일 21시 종료. 휴식시간·주문 마감 별도 확인.",
      "id": "jalppajin",
      "region": "seochon",
      "phone": "0507-1403-1214",
      "extraSource": "https://www.instagram.com/jalppajin_seochon",
      "englishName": "Jalppajin Memil Seochon",
      "source": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=60129",
      "sourceLabel": "한국관광공사 장소 안내",
      "coords": [
        37.5797840630322,
        126.971077347576
      ],
      "locationSource": "legacy",
      "locationSourceUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=60129",
      "photoSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=60129",
      "photoAuthor": "한국관광공사 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/jalppajin.jpg",
      "preview": "images/places/optimized/jalppajin-480.webp",
      "largePreview": "images/places/optimized/jalppajin-960.webp",
      "imageAlt": "잘빠진메밀 서촌 · 공식 안내의 매장 외관 · 현재 입구 확인",
      "hoursSummary": "월–토 11–21:30 · 일 21시 종료 · 휴식시간·주문 마감 별도 확인",
      "checkUrl": "https://www.instagram.com/jalppajin_seochon",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=60129"
    },
    {
      "useMode": "메뉴별 주문·결제",
      "accessSummary": "좌석·출입구 단차는 매장에 확인",
      "access": "휠체어·유모차 진입과 화장실 동선은 현장 확인이 필요합니다.",
      "unknown": "당일 대기·가격, 재료와 알레르기 대응, 휴식시간, 무단차 좌석",
      "checkLabel": "메뉴·운영 안내",
      "name": "깊은",
      "category": "식당 · 국밥·숯불 요리",
      "visitWhen": "엉겅퀴 해장국과 숯불 요리 고르기",
      "cost": "메뉴별 결제 · 현재 메뉴 확인",
      "schedule": "관광 안내 11:30–22시",
      "closure": "휴식시간·예약 가능 여부 확인",
      "description": "안국역 남쪽 인사동16길의 국밥·숯불 요리 식당입니다. 관광재단은 영어 메뉴와 비건 선택지를 안내하지만, 가능한 메뉴는 주문 전에 확인하세요.",
      "address": "서울 종로구 인사동16길 6",
      "visitTip": "안국역 남측 권역입니다. 비건 메뉴 유무와 별개로 알레르기·교차 접촉 대응, 예약 좌석은 매장에 확인하세요.",
      "photoLabel": "요리 참고 사진 · 메뉴 구성은 확인",
      "hours": "관광 안내 11:30–22시. 휴식시간·예약 가능 여부 확인.",
      "id": "gippen",
      "region": "anguk",
      "englishName": "GIPPEN",
      "source": "https://english.visitseoul.net/restaurants/GIPPEN/ENPl3xyt0",
      "sourceLabel": "서울관광재단 장소 안내",
      "coords": [
        37.575017290578,
        126.984242826008
      ],
      "locationSource": "서울관광재단 장소 좌표",
      "locationSourceUrl": "https://english.visitseoul.net/restaurants/GIPPEN/ENPl3xyt0",
      "photoSource": "https://english.visitseoul.net/restaurants/GIPPEN/ENPl3xyt0",
      "photoAuthor": "서울관광재단 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/gippen.jpg",
      "preview": "images/places/optimized/gippen-480.webp",
      "largePreview": "images/places/optimized/gippen-960.webp",
      "imageAlt": "깊은 · 요리 참고 사진 · 메뉴 구성은 확인",
      "hoursSummary": "관광 안내 11:30–22시 · 휴식시간·예약 가능 여부 확인",
      "checkUrl": "https://english.visitseoul.net/restaurants/GIPPEN/ENPl3xyt0",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitseoul.net/restaurants/GIPPEN/ENPl3xyt0"
    },
    {
      "useMode": "메뉴별 주문·결제",
      "accessSummary": "좌석·출입구 단차는 매장에 확인",
      "access": "휠체어·유모차 진입과 화장실 동선은 현장 확인이 필요합니다.",
      "unknown": "당일 대기·가격, 재료와 알레르기 대응, 휴식시간, 무단차 좌석",
      "checkLabel": "메뉴·운영 안내",
      "name": "삼청동수제비",
      "category": "식당 · 수제비",
      "visitWhen": "수제비와 감자전으로 식사하기",
      "cost": "메뉴별 결제 · 현재 가격 확인",
      "schedule": "11시 개점 · 종료시간 확인",
      "closure": "임시 휴무·주문 마감 확인",
      "description": "삼청로 북쪽의 수제비 식당입니다. 안국역 바로 앞은 아니므로 지도에서 위치를 보고, 면 요리와 국밥 중 원하는 한 끼를 고르세요.",
      "address": "서울 종로구 삼청로 101-1",
      "visitTip": "서울관광재단은 20시, 다른 관광 안내는 21시 종료로 기재합니다. 늦게 방문한다면 확인하고, 밀·조개류 등 재료도 주문 전 문의하세요.",
      "photoLabel": "식당 외관",
      "hours": "11시 개점 · 종료시간 확인. 임시 휴무·주문 마감 확인.",
      "id": "sujebi",
      "region": "anguk",
      "phone": "02-735-2965",
      "englishName": "Samcheong-dong Sujebi",
      "source": "https://english.visitseoul.net/area/Samcheong-dongSujebi/ENPqgbap0",
      "sourceLabel": "서울관광재단 장소 안내",
      "coords": [
        37.5846110994267,
        126.981908523675
      ],
      "locationSource": "서울관광재단 장소 좌표",
      "locationSourceUrl": "https://english.visitseoul.net/area/Samcheong-dongSujebi/ENPqgbap0",
      "photoSource": "https://english.visitseoul.net/area/Samcheong-dongSujebi/ENPqgbap0",
      "photoAuthor": "서울관광재단 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/sujebi.jpg",
      "preview": "images/places/optimized/sujebi-480.webp",
      "largePreview": "images/places/optimized/sujebi-960.webp",
      "imageAlt": "삼청동수제비 · 식당 외관",
      "hoursSummary": "11시 개점 · 종료시간 확인 · 임시 휴무·주문 마감 확인",
      "checkUrl": "https://english.visitseoul.net/area/Samcheong-dongSujebi/ENPqgbap0",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitseoul.net/area/Samcheong-dongSujebi/ENPqgbap0"
    },
    {
      "useMode": "음료·디저트 주문 · 좌석 이용 조건 확인",
      "accessSummary": "좌식·의자석과 출입구 단차 확인",
      "access": "좌석과 층별 이동 경로는 매장마다 다릅니다. 필요한 좌석·무단차 경로를 방문 전에 문의하세요.",
      "unknown": "현재 가격·좌석·대기, 카페인·알레르기, 계단 없는 이용, 상품 재고",
      "checkLabel": "매장 방문 안내",
      "name": "런던베이글뮤지엄 안국점",
      "category": "베이커리 · 베이글",
      "visitWhen": "베이글을 골라 먹거나 포장하기",
      "cost": "베이글·음료별 결제",
      "schedule": "기본 08–18시",
      "closure": "대기 접수·품절·마감 확인",
      "description": "안국의 베이글 전문점입니다. 원하는 메뉴를 사는 것이 목적인지, 차를 마시며 머무는 것이 목적인지 비교해 선택하세요.",
      "address": "서울 종로구 북촌로4길 20",
      "visitTip": "현장·원격 대기 방식과 포장 가능 여부는 매장 안내를 확인하세요. 이 앱은 실시간 대기 순번이나 재고를 제공하지 않습니다.",
      "photoLabel": "베이글 진열 · 현재 재고 아님",
      "hours": "기본 08–18시. 대기 접수·품절·마감 확인.",
      "id": "london",
      "region": "anguk",
      "englishName": "London Bagel Museum Anguk",
      "source": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=191147",
      "sourceLabel": "한국관광공사 장소 안내",
      "coords": [
        37.5791705224607,
        126.986200889348
      ],
      "locationSource": "한국관광공사 장소 좌표",
      "locationSourceUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=191147",
      "photoSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=191147",
      "photoAuthor": "한국관광공사 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/london.jpg",
      "preview": "images/places/optimized/london-480.webp",
      "largePreview": "images/places/optimized/london-960.webp",
      "imageAlt": "런던베이글뮤지엄 안국점 · 베이글 진열 · 현재 재고 아님",
      "hoursSummary": "기본 08–18시 · 대기 접수·품절·마감 확인",
      "checkUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=191147",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=191147"
    },
    {
      "useMode": "음료·디저트 주문 · 좌석 이용 조건 확인",
      "accessSummary": "좌식·의자석과 출입구 단차 확인",
      "access": "좌석과 층별 이동 경로는 매장마다 다릅니다. 필요한 좌석·무단차 경로를 방문 전에 문의하세요.",
      "unknown": "현재 가격·좌석·대기, 카페인·알레르기, 계단 없는 이용, 상품 재고",
      "checkLabel": "매장 방문 안내",
      "name": "오설록 티하우스 북촌점",
      "category": "티하우스 · 차·디저트",
      "visitWhen": "차와 차를 활용한 디저트 즐기기",
      "cost": "음료·디저트·상품별 결제",
      "schedule": "관광 안내 11–20시",
      "closure": "층별 운영·주문 마감 확인",
      "description": "북촌로의 티하우스로 차 음료, 디저트와 차 상품을 만날 수 있습니다. 카페 이용과 여행 선물 구매는 각각의 비용을 확인하세요.",
      "address": "서울 종로구 북촌로 45",
      "visitTip": "체험·티코스는 일반 음료 주문과 다를 수 있습니다. 예약, 카페인과 선물 포장·재고를 확인하세요.",
      "photoLabel": "티하우스 건물 외관",
      "hours": "관광 안내 11–20시. 층별 운영·주문 마감 확인.",
      "id": "osulloc",
      "region": "anguk",
      "phone": "070-4121-2019",
      "extraSource": "https://access.visitkorea.or.kr/food/detail.do?cotId=2f8ed3f7-9ab0-489e-a03c-20a9d5700bdc",
      "englishName": "Osulloc Tea House Bukchon",
      "source": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=1573739",
      "sourceLabel": "한국관광공사 장소 안내",
      "coords": [
        37.5809985877276,
        126.984600900483
      ],
      "locationSource": "한국관광공사 장소 좌표",
      "locationSourceUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=1573739",
      "photoSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=1573739",
      "photoAuthor": "한국관광공사 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/osulloc.jpg",
      "preview": "images/places/optimized/osulloc-480.webp",
      "largePreview": "images/places/optimized/osulloc-960.webp",
      "imageAlt": "오설록 티하우스 북촌점 · 티하우스 건물 외관",
      "hoursSummary": "관광 안내 11–20시 · 층별 운영·주문 마감 확인",
      "checkUrl": "https://access.visitkorea.or.kr/food/detail.do?cotId=2f8ed3f7-9ab0-489e-a03c-20a9d5700bdc",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=1573739"
    },
    {
      "useMode": "음료·디저트 주문 · 좌석 이용 조건 확인",
      "accessSummary": "좌식·의자석과 출입구 단차 확인",
      "access": "좌석과 층별 이동 경로는 매장마다 다릅니다. 필요한 좌석·무단차 경로를 방문 전에 문의하세요.",
      "unknown": "현재 가격·좌석·대기, 카페인·알레르기, 계단 없는 이용, 상품 재고",
      "checkLabel": "매장 방문 안내",
      "name": "차마시는뜰",
      "category": "찻집 · 한옥·전통차",
      "visitWhen": "한옥에서 전통차와 다과 즐기기",
      "cost": "차·다과별 결제",
      "schedule": "10–19시 · 주문 마감 18:10 안내",
      "closure": "화요일 휴무 · 명절 확인",
      "description": "한옥의 낮은 상에서 전통차와 다과를 즐기는 찻집입니다. 좌식이 편한지, 의자석이 필요한지 먼저 생각해 보세요.",
      "address": "서울 종로구 북촌로11나길 26",
      "visitTip": "북촌 주거 골목의 관광 방문시간·현장 표지를 먼저 확인하세요. 매장 영업시간이 골목 출입 가능 시간을 뜻하지는 않습니다.",
      "photoLabel": "한옥 입구 · 야간 참고 사진",
      "hours": "10–19시 · 주문 마감 18:10 안내. 화요일 휴무 · 명절 확인.",
      "id": "chatteul",
      "region": "anguk",
      "phone": "0507-1304-7029",
      "englishName": "Chamasineun Tteul",
      "source": "https://english.visitseoul.net/PalaceArea/Cha-teul/ENP139gfg",
      "sourceLabel": "서울관광재단 장소 안내",
      "coords": [
        37.5822190175845,
        126.982274443699
      ],
      "locationSource": "서울관광재단 장소 좌표",
      "locationSourceUrl": "https://english.visitseoul.net/PalaceArea/Cha-teul/ENP139gfg",
      "photoSource": "https://english.visitseoul.net/PalaceArea/Cha-teul/ENP139gfg",
      "photoAuthor": "서울관광재단 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/chatteul.jpg",
      "preview": "images/places/optimized/chatteul-480.webp",
      "largePreview": "images/places/optimized/chatteul-960.webp",
      "imageAlt": "차마시는뜰 · 한옥 입구 · 야간 참고 사진",
      "hoursSummary": "10–19시 · 주문 마감 18:10 안내 · 화요일 휴무 · 명절 확인",
      "checkUrl": "https://english.visitseoul.net/PalaceArea/Cha-teul/ENP139gfg",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitseoul.net/PalaceArea/Cha-teul/ENP139gfg"
    },
    {
      "useMode": "음료·디저트 주문 · 좌석 이용 조건 확인",
      "accessSummary": "좌식·의자석과 출입구 단차 확인",
      "access": "좌석과 층별 이동 경로는 매장마다 다릅니다. 필요한 좌석·무단차 경로를 방문 전에 문의하세요.",
      "unknown": "현재 가격·좌석·대기, 카페인·알레르기, 계단 없는 이용, 상품 재고",
      "checkLabel": "매장 방문 안내",
      "name": "프릳츠 원서",
      "category": "카페 · 커피·빵",
      "visitWhen": "원서동에서 커피와 빵 즐기기",
      "cost": "음료·빵·상품별 결제",
      "schedule": "관광 안내 10–21시 · 매장 재확인",
      "closure": "임시 휴무·주문 마감 확인",
      "description": "아라리오뮤지엄 옆 원서점에서 커피와 빵을 주문할 수 있습니다. 미술관 관람과 카페 이용은 별개의 선택입니다.",
      "address": "서울 종로구 율곡로 83",
      "visitTip": "공식 매장 안내에서 원서점을 선택하세요. 선물용 원두·드립백은 해당 지점 재고를 확인하고, 미술관 개관시간을 카페 시간으로 적용하지 마세요.",
      "photoLabel": "한옥 공간 외관",
      "hours": "관광 안내 10–21시 · 매장 재확인. 임시 휴무·주문 마감 확인.",
      "id": "fritz",
      "region": "anguk",
      "phone": "02-747-8101",
      "extraSource": "https://fritz.co.kr/store.html",
      "englishName": "Fritz Coffee Wonseo",
      "source": "https://english.visitseoul.net/hallyu/Walking-Through-Wonseo-dong-Alleyways/30586",
      "sourceLabel": "서울관광재단 장소 안내",
      "coords": [
        37.5777021,
        126.9885964
      ],
      "locationSource": "운영자 연결 지도",
      "locationSourceUrl": "https://maps.app.goo.gl/ERXjkcyKVRqJkViFA",
      "photoSource": "https://english.visitseoul.net/hallyu/Walking-Through-Wonseo-dong-Alleyways/30586",
      "photoAuthor": "서울관광재단 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/fritz.jpg",
      "preview": "images/places/optimized/fritz-480.webp",
      "largePreview": "images/places/optimized/fritz-960.webp",
      "imageAlt": "프릳츠 원서 · 한옥 공간 외관",
      "hoursSummary": "관광 안내 10–21시 · 매장 재확인 · 임시 휴무·주문 마감 확인",
      "checkUrl": "https://fritz.co.kr/store.html",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitseoul.net/hallyu/Walking-Through-Wonseo-dong-Alleyways/30586"
    },
    {
      "useMode": "음료·디저트 주문 · 좌석 이용 조건 확인",
      "accessSummary": "좌식·의자석과 출입구 단차 확인",
      "access": "좌석과 층별 이동 경로는 매장마다 다릅니다. 필요한 좌석·무단차 경로를 방문 전에 문의하세요.",
      "unknown": "현재 가격·좌석·대기, 카페인·알레르기, 계단 없는 이용, 상품 재고",
      "checkLabel": "매장 방문 안내",
      "name": "티테라피",
      "category": "찻집 · 블렌딩 차",
      "visitWhen": "허브·과일차를 취향대로 고르기",
      "cost": "차·상품 유료 · 체험 별도 확인",
      "schedule": "월–토 10–21시 · 일 20시 종료",
      "closure": "계절별 변경·체험 일정 확인",
      "description": "윤보선길의 찻집으로 허브·과일을 활용한 차와 차 상품을 소개합니다. 맛과 향을 중심으로 고르고, 원데이 차 프로그램은 별도 문의하세요.",
      "address": "서울 종로구 윤보선길 74",
      "visitTip": "차 수업·족욕의 당일 운영, 비용과 예약을 문의하세요. 차의 건강 효과를 이 앱에서 판단하거나 보장하지 않습니다.",
      "photoLabel": "찻집 외관",
      "hours": "월–토 10–21시 · 일 20시 종료. 계절별 변경·체험 일정 확인.",
      "id": "teatherapy",
      "region": "anguk",
      "phone": "02-730-7507",
      "extraSource": "https://english.visitseoul.net/restaurants/Four-wellness-cafes-in-Seoul/ENN032527",
      "englishName": "Tea Therapy",
      "source": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=188076",
      "sourceLabel": "한국관광공사 장소 안내",
      "coords": [
        37.5791621422181,
        126.983551148135
      ],
      "locationSource": "한국관광공사 장소 좌표",
      "locationSourceUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=188076",
      "photoSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=188076",
      "photoAuthor": "한국관광공사 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/teatherapy.jpg",
      "preview": "images/places/optimized/teatherapy-480.webp",
      "largePreview": "images/places/optimized/teatherapy-960.webp",
      "imageAlt": "티테라피 · 찻집 외관",
      "hoursSummary": "월–토 10–21시 · 일 20시 종료 · 계절별 변경·체험 일정 확인",
      "checkUrl": "https://english.visitseoul.net/restaurants/Four-wellness-cafes-in-Seoul/ENN032527",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=188076"
    },
    {
      "useMode": "전시 일정·관람권·입장 마감 확인 후 관람",
      "accessSummary": "전시실별 계단·엘리베이터 동선 확인",
      "access": "전시실과 건물에 따라 단차·계단이 있을 수 있습니다. 필요한 이동 지원을 운영기관에 문의하세요.",
      "unknown": "현재 전시·요금·휴관, 촬영 규칙, 연령 제한, 무단차 경로",
      "checkLabel": "전시·관람 안내",
      "name": "종로구립 박노수미술관",
      "category": "미술관 · 작가의 집",
      "visitWhen": "작가의 집과 한국화 살펴보기",
      "cost": "성인 3,000원 안내 · 감면 확인",
      "schedule": "기본 10–18시",
      "closure": "월요일·1월 1일·설·추석 휴관 안내",
      "description": "화가 박노수가 살던 집에서 작품과 정원을 함께 보는 미술관입니다. 여러 층의 기획전시를 보는 일정과 작은 작가의 집을 둘러보는 일정을 비교하세요.",
      "address": "서울 종로구 옥인1길 34",
      "visitTip": "외관 사진에 계단이 보입니다. 내부 진입, 정원 이용과 전시 교체 기간을 확인하세요.",
      "photoLabel": "작가의 집 외관 · 계단 있는 진입부",
      "hours": "기본 10–18시. 월요일·1월 1일·설·추석 휴관 안내.",
      "id": "park",
      "region": "seochon",
      "phone": "02-2148-4171",
      "englishName": "Park No-soo Museum",
      "source": "https://english.visitseoul.net/museum/ParkNoSoo-Museum/ENP042350",
      "sourceLabel": "서울관광재단 장소 안내",
      "coords": [
        37.5813191962491,
        126.966818545949
      ],
      "locationSource": "서울관광재단 장소 좌표",
      "locationSourceUrl": "https://english.visitseoul.net/museum/ParkNoSoo-Museum/ENP042350",
      "photoSource": "https://english.visitseoul.net/museum/ParkNoSoo-Museum/ENP042350",
      "photoAuthor": "서울관광재단 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/park.jpg",
      "preview": "images/places/optimized/park-480.webp",
      "largePreview": "images/places/optimized/park-960.webp",
      "imageAlt": "종로구립 박노수미술관 · 작가의 집 외관 · 계단 있는 진입부",
      "hoursSummary": "기본 10–18시 · 월요일·1월 1일·설·추석 휴관 안내",
      "checkUrl": "https://english.visitseoul.net/museum/ParkNoSoo-Museum/ENP042350",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitseoul.net/museum/ParkNoSoo-Museum/ENP042350"
    },
    {
      "useMode": "전시 일정·관람권·입장 마감 확인 후 관람",
      "accessSummary": "전시실별 계단·엘리베이터 동선 확인",
      "access": "전시실과 건물에 따라 단차·계단이 있을 수 있습니다. 필요한 이동 지원을 운영기관에 문의하세요.",
      "unknown": "현재 전시·요금·휴관, 촬영 규칙, 연령 제한, 무단차 경로",
      "checkLabel": "전시·관람 안내",
      "name": "대림미술관",
      "category": "미술관 · 기획전시",
      "visitWhen": "사진·디자인 등 기획전시 고르기",
      "cost": "전시별 요금·예매 확인",
      "schedule": "현재 전시의 관람시간 확인",
      "closure": "월요일 등 휴관·전시 교체 확인",
      "description": "통의동의 기획전 중심 미술관입니다. 전시마다 주제, 관람료와 운영시간이 바뀔 수 있어 현재 열리는 전시부터 살펴보세요.",
      "address": "서울 종로구 자하문로4길 21",
      "visitTip": "서울숲의 디뮤지엄과 다른 장소입니다. 이전 관광자료의 관람료 대신 대림미술관의 현재 전시 예매 조건을 확인하세요.",
      "photoLabel": "미술관 외관 · 현재 전시 사진 아님",
      "hours": "현재 전시의 관람시간 확인. 월요일 등 휴관·전시 교체 확인.",
      "id": "daelim",
      "region": "seochon",
      "phone": "02-720-0667",
      "extraSource": "https://www.daelimmuseum.org/",
      "englishName": "Daelim Museum",
      "source": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=89412",
      "sourceLabel": "한국관광공사 장소 안내",
      "coords": [
        37.5774482773549,
        126.973321639678
      ],
      "locationSource": "한국관광공사 장소 좌표",
      "locationSourceUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=89412",
      "photoSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=89412",
      "photoAuthor": "한국관광공사 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/daelim.jpg",
      "preview": "images/places/optimized/daelim-480.webp",
      "largePreview": "images/places/optimized/daelim-960.webp",
      "imageAlt": "대림미술관 · 미술관 외관 · 현재 전시 사진 아님",
      "hoursSummary": "현재 전시의 관람시간 확인 · 월요일 등 휴관·전시 교체 확인",
      "checkUrl": "https://www.daelimmuseum.org/",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=89412"
    },
    {
      "useMode": "전시 일정·관람권·입장 마감 확인 후 관람",
      "accessSummary": "전시실별 계단·엘리베이터 동선 확인",
      "access": "전시실과 건물에 따라 단차·계단이 있을 수 있습니다. 필요한 이동 지원을 운영기관에 문의하세요.",
      "unknown": "현재 전시·요금·휴관, 촬영 규칙, 연령 제한, 무단차 경로",
      "checkLabel": "전시·관람 안내",
      "name": "학고재",
      "category": "갤러리 · 현대미술",
      "visitWhen": "한옥과 현대 전시실에서 작품 보기",
      "cost": "일반 전시 무료 안내 · 현재 전시 확인",
      "schedule": "기본 10–18시",
      "closure": "일·월요일 휴관 안내 · 전시 교체 확인",
      "description": "삼청로의 한옥 본관과 현대식 전시 공간을 가진 갤러리입니다. 큰 미술관의 여러 전시와, 갤러리의 현재 전시를 비교해 보세요.",
      "address": "서울 종로구 삼청로 50",
      "visitTip": "같은 갤러리도 전시 교체일에는 닫을 수 있습니다. 촬영·큰 가방·단체 방문 조건을 확인하세요.",
      "photoLabel": "한옥 갤러리 외관",
      "hours": "기본 10–18시. 일·월요일 휴관 안내 · 전시 교체 확인.",
      "id": "hakgojae",
      "region": "anguk",
      "phone": "02-720-1524",
      "extraSource": "https://www.hakgojae.com/",
      "englishName": "Hakgojae Gallery",
      "source": "https://english.visitseoul.net/attractions/hakgojae-gallery/ENP001871",
      "sourceLabel": "서울관광재단 장소 안내",
      "coords": [
        37.580321,
        126.980294
      ],
      "locationSource": "서울관광재단 장소 좌표",
      "locationSourceUrl": "https://english.visitseoul.net/attractions/hakgojae-gallery/ENP001871",
      "photoSource": "https://english.visitseoul.net/attractions/hakgojae-gallery/ENP001871",
      "photoAuthor": "서울관광재단 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/hakgojae.jpg",
      "preview": "images/places/optimized/hakgojae-480.webp",
      "largePreview": "images/places/optimized/hakgojae-960.webp",
      "imageAlt": "학고재 · 한옥 갤러리 외관",
      "hoursSummary": "기본 10–18시 · 일·월요일 휴관 안내 · 전시 교체 확인",
      "checkUrl": "https://www.hakgojae.com/",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitseoul.net/attractions/hakgojae-gallery/ENP001871"
    },
    {
      "useMode": "전시 일정·관람권·입장 마감 확인 후 관람",
      "accessSummary": "전시실별 계단·엘리베이터 동선 확인",
      "access": "전시실과 건물에 따라 단차·계단이 있을 수 있습니다. 필요한 이동 지원을 운영기관에 문의하세요.",
      "unknown": "현재 전시·요금·휴관, 촬영 규칙, 연령 제한, 무단차 경로",
      "checkLabel": "전시·관람 안내",
      "name": "보안1942",
      "category": "예술공간 · 옛 여관",
      "visitWhen": "옛 여관의 공간과 전시 살펴보기",
      "cost": "전시별 확인 · 책·음료 별도 구매",
      "schedule": "전시장 기본 화–일 12–18시",
      "closure": "월요일 휴관 · 공간별 시간 상이",
      "description": "옛 보안여관을 활용한 전시공간과 책방 등이 함께 있는 문화공간입니다. 작품뿐 아니라 건물에 남은 흔적을 보는 방문을 제안합니다.",
      "address": "서울 종로구 효자로 33",
      "visitTip": "전시장·책방·카페·숙박은 시간과 이용 조건이 다릅니다. 옛 건물의 층간 계단, 전시 공백기와 개방 구역을 확인하세요.",
      "photoLabel": "과거 전시가 보이는 실내 · 현재 전시 아님",
      "hours": "전시장 기본 화–일 12–18시. 월요일 휴관 · 공간별 시간 상이.",
      "id": "boan",
      "region": "seochon",
      "phone": "02-720-8409",
      "extraSource": "https://b1942.com/",
      "englishName": "Boan1942",
      "source": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=175341",
      "sourceLabel": "한국관광공사 장소 안내",
      "coords": [
        37.5791091918353,
        126.973649338076
      ],
      "locationSource": "한국관광공사 장소 좌표",
      "locationSourceUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=175341",
      "photoSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=175341",
      "photoAuthor": "한국관광공사 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/boan.jpg",
      "preview": "images/places/optimized/boan-480.webp",
      "largePreview": "images/places/optimized/boan-960.webp",
      "imageAlt": "보안1942 · 과거 전시가 보이는 실내 · 현재 전시 아님",
      "hoursSummary": "전시장 기본 화–일 12–18시 · 월요일 휴관 · 공간별 시간 상이",
      "checkUrl": "https://b1942.com/",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=175341"
    },
    {
      "useMode": "일반 개방 구역 관람 · 해설·체험은 별도 조건",
      "accessSummary": "한옥 문턱·마당과 개방 구역 확인",
      "access": "마당과 실내의 단차가 다릅니다. 유모차·휠체어로 방문할 경우 이용 가능한 구역을 문의하세요.",
      "unknown": "당일 개방 구역·해설 잔여석, 프로그램 비용·언어, 무단차 경로",
      "checkLabel": "관람·프로그램 안내",
      "name": "백인제가옥",
      "category": "한옥 · 근대 주거",
      "visitWhen": "큰 한옥의 마당과 생활 공간 살펴보기",
      "cost": "일반 관람 무료 · 내부 해설 별도 예약",
      "schedule": "09–18시 · 입장 마감 17:30",
      "closure": "월요일·1월 1일 휴관 안내",
      "description": "근대 한옥의 구조와 정원을 살펴볼 수 있는 가옥입니다. 일반 방문은 외부 개방 구역을 중심으로 하며, 일부 실내는 해설 예약이 필요합니다.",
      "address": "서울 종로구 북촌로7길 16",
      "visitTip": "예약 없이 모든 실내에 들어갈 수 있는 곳은 아닙니다. 원하는 관람 구역, 해설 언어·시간과 어린이 동반 조건을 확인하세요.",
      "photoLabel": "가옥 입구 · 계단 있는 진입부",
      "hours": "09–18시 · 입장 마감 17:30. 월요일·1월 1일 휴관 안내.",
      "id": "baekinje",
      "region": "anguk",
      "extraSource": "https://english.visitseoul.net/attractions/Baek-Injes-House/ENP021128",
      "englishName": "Baek In-je House",
      "source": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=64978",
      "sourceLabel": "한국관광공사 장소 안내",
      "coords": [
        37.5803870019372,
        126.984053841886
      ],
      "locationSource": "한국관광공사 장소 좌표",
      "locationSourceUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=64978",
      "photoSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=64978",
      "photoAuthor": "한국관광공사 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/baekinje.jpg",
      "preview": "images/places/optimized/baekinje-480.webp",
      "largePreview": "images/places/optimized/baekinje-960.webp",
      "imageAlt": "백인제가옥 · 가옥 입구 · 계단 있는 진입부",
      "hoursSummary": "09–18시 · 입장 마감 17:30 · 월요일·1월 1일 휴관 안내",
      "checkUrl": "https://english.visitseoul.net/attractions/Baek-Injes-House/ENP021128",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=64978"
    },
    {
      "useMode": "일반 개방 구역 관람 · 해설·체험은 별도 조건",
      "accessSummary": "한옥 문턱·마당과 개방 구역 확인",
      "access": "마당과 실내의 단차가 다릅니다. 유모차·휠체어로 방문할 경우 이용 가능한 구역을 문의하세요.",
      "unknown": "당일 개방 구역·해설 잔여석, 프로그램 비용·언어, 무단차 경로",
      "checkLabel": "관람·프로그램 안내",
      "name": "상촌재",
      "category": "한옥 · 온돌 문화",
      "visitWhen": "한옥과 온돌의 구조 살펴보기",
      "cost": "일반 관람 무료 · 프로그램 별도",
      "schedule": "기본 09–18시",
      "closure": "월요일·1월 1일·설·추석 휴관 확인",
      "description": "서촌의 한옥 문화공간으로 온돌과 전통 생활문화를 소개합니다. 계절 행사와 교육은 매일 열리는 프로그램이 아니므로 따로 확인하세요.",
      "address": "서울 종로구 자하문로17길 12-11",
      "visitTip": "관람 무료와 체험 무료는 다릅니다. 프로그램 신청·재료비·진행 언어와 마당 개방 범위를 확인하세요.",
      "photoLabel": "한옥 문화공간 참고 사진",
      "hours": "기본 09–18시. 월요일·1월 1일·설·추석 휴관 확인.",
      "id": "sangchon",
      "region": "seochon",
      "phone": "02-6013-1142",
      "extraSource": "https://www.jfac.or.kr/site/main/content/sangchj01",
      "englishName": "Sangchonjae",
      "source": "https://english.visitseoul.net/editorspicks/Sangchonjae-Cultural-Space/ENN037775",
      "sourceLabel": "서울관광재단 장소 안내",
      "coords": [
        37.5818637908297,
        126.96962237201
      ],
      "locationSource": "한국관광공사 장소 좌표",
      "locationSourceUrl": "https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=175347",
      "photoSource": "https://english.visitseoul.net/editorspicks/Sangchonjae-Cultural-Space/ENN037775",
      "photoAuthor": "서울관광재단 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/sangchon.jpg",
      "preview": "images/places/optimized/sangchon-480.webp",
      "largePreview": "images/places/optimized/sangchon-960.webp",
      "imageAlt": "상촌재 · 한옥 문화공간 참고 사진",
      "hoursSummary": "기본 09–18시 · 월요일·1월 1일·설·추석 휴관 확인",
      "checkUrl": "https://www.jfac.or.kr/site/main/content/sangchj01",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitseoul.net/editorspicks/Sangchonjae-Cultural-Space/ENN037775"
    },
    {
      "useMode": "공원 개방 구간 산책 · 문화유산 내부는 별도",
      "accessSummary": "야외 경사·보행로와 현장 통제 확인",
      "access": "공원 안에서도 경사·단차와 개방 구간이 다릅니다. 우천·공사·행사 시 현장 안내를 따르세요.",
      "unknown": "당일 통제·행사, 화장실 개방, 무단차 산책 구간",
      "checkLabel": "공원 이용 안내",
      "name": "사직공원",
      "category": "공원 · 야외 산책",
      "visitWhen": "공원 길을 따라 쉬엄쉬엄 걷기",
      "cost": "공원 산책 무료 · 시설별 조건 별도",
      "schedule": "공원 상시 개방 안내",
      "closure": "사직단·시설 내부와 행사 통제 별도",
      "description": "사직단 주변의 공원 구역입니다. 산자락 계곡까지 오르기보다 공원에서 걷고 싶을 때 비교하세요. 사직단 내부를 자유롭게 이용한다는 뜻은 아닙니다.",
      "address": "서울 종로구 사직로 89",
      "visitTip": "아이와 함께라면 문화유산 구역과 일반 산책 구간을 구분하고, 비·더위에는 실내 비교를 선택하세요.",
      "photoLabel": "사직단 풍경 · 자유 출입 보장 아님",
      "hours": "공원 상시 개방 안내. 사직단·시설 내부와 행사 통제 별도.",
      "id": "sajik",
      "region": "seochon",
      "englishName": "Sajik Park Seoul",
      "source": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=86285",
      "sourceLabel": "한국관광공사 장소 안내",
      "coords": [
        37.5756539494647,
        126.967663909629
      ],
      "locationSource": "한국관광공사 장소 좌표",
      "locationSourceUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=86285",
      "photoSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=86285",
      "photoAuthor": "한국관광공사 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/sajik.jpg",
      "preview": "images/places/optimized/sajik-480.webp",
      "largePreview": "images/places/optimized/sajik-960.webp",
      "imageAlt": "사직공원 · 사직단 풍경 · 자유 출입 보장 아님",
      "hoursSummary": "공원 상시 개방 안내 · 사직단·시설 내부와 행사 통제 별도",
      "checkUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=86285",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=86285"
    },
    {
      "useMode": "일반 개방 구역 관람 · 해설·체험은 별도 조건",
      "accessSummary": "한옥 문턱·마당과 개방 구역 확인",
      "access": "마당과 실내의 단차가 다릅니다. 유모차·휠체어로 방문할 경우 이용 가능한 구역을 문의하세요.",
      "unknown": "당일 개방 구역·해설 잔여석, 프로그램 비용·언어, 무단차 경로",
      "checkLabel": "관람·프로그램 안내",
      "name": "동림매듭공방",
      "category": "공방 · 전통 매듭",
      "visitWhen": "매듭 장식을 보고 직접 만들기",
      "cost": "체험·작품별 유료 · 현재 비용 확인",
      "schedule": "기본 10–18시",
      "closure": "월요일·명절 휴무 안내",
      "description": "전통 매듭 작품을 전시하고 팔찌·장식 등을 만드는 체험을 운영하는 한옥 공방입니다. 체험 종류와 재료비는 선택한 작업에 따라 다릅니다.",
      "address": "서울 종로구 북촌로12길 10",
      "visitTip": "예약 가능 시간, 소요시간, 설명 언어와 어린이 참여 가능 연령을 문의하세요. 전시 관람과 만들기를 구분해 신청하세요.",
      "photoLabel": "매듭 공방 한옥 외관",
      "hours": "기본 10–18시. 월요일·명절 휴무 안내.",
      "id": "donglim",
      "region": "anguk",
      "phone": "02-3673-2778",
      "extraSource": "https://english.visitseoul.net/attractions/donglim-knot-workshop_/18964",
      "englishName": "Donglim Knot Workshop",
      "source": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=97767",
      "sourceLabel": "한국관광공사 장소 안내",
      "coords": [
        37.5817368650513,
        126.985586987069
      ],
      "locationSource": "한국관광공사 장소 좌표",
      "locationSourceUrl": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=97767",
      "photoSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=97767",
      "photoAuthor": "한국관광공사 게시 · 원본 표기 유지",
      "photoDate": "촬영일 미상",
      "image": "images/places/donglim.jpg",
      "preview": "images/places/optimized/donglim-480.webp",
      "largePreview": "images/places/optimized/donglim-960.webp",
      "imageAlt": "동림매듭공방 · 매듭 공방 한옥 외관",
      "hoursSummary": "기본 10–18시 · 월요일·명절 휴무 안내",
      "checkUrl": "https://english.visitseoul.net/attractions/donglim-knot-workshop_/18964",
      "review": {
        "checkedAt": "2026-09-30",
        "fields": "공개 방문 안내·주소·대표 위치",
        "note": "자료 열람일 기준 · 당일 운영·가격·예약은 방문 전 확인"
      },
      "englishSource": "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=97767"
    }
  ],
  "categories": [
    {
      "id": "all",
      "label": "모두"
    },
    {
      "id": "food",
      "label": "먹거리"
    },
    {
      "id": "cafe",
      "label": "카페·차"
    },
    {
      "id": "rest",
      "label": "쉬기·산책"
    },
    {
      "id": "culture",
      "label": "문화·역사"
    },
    {
      "id": "art",
      "label": "미술·전시"
    },
    {
      "id": "make",
      "label": "체험·선물"
    },
    {
      "id": "weather",
      "label": "비·더위"
    },
    {
      "id": "family",
      "label": "아이와"
    },
    {
      "id": "free",
      "label": "무료 관람"
    }
  ],
  "pairs": [
    {
      "id": "soup-choice",
      "region": "anguk",
      "category": "food",
      "placeIds": [
        "sujebi",
        "gippen"
      ],
      "title": "수제비 한 그릇, 국밥 한 그릇",
      "reason": "삼청로의 수제비와 안국역 남측의 국밥·숯불 요리를 비교해요.",
      "notice": "두 곳은 안국 권역의 서로 다른 쪽에 있어요. 현재 위치에서 갈 곳을 지도로 확인하세요.",
      "shortTitle": "수제비 한 그릇, 국밥 한 그릇",
      "regionLabel": "안국",
      "choices": {}
    },
    {
      "id": "seochon-noodle-grill",
      "region": "seochon",
      "category": "food",
      "placeIds": [
        "chebu",
        "jalppajin"
      ],
      "title": "갈비를 나눠 먹을까, 메밀국수를 먹을까?",
      "reason": "테이블에서 굽는 고기와 면·수육 중심 식사의 차이를 살펴요.",
      "notice": "현재 메뉴·주문 인원·휴식시간을 확인하세요. 메밀면만으로 채식·알레르기 대응을 판단하지 마세요.",
      "shortTitle": "갈비를 나눠 먹을까, 메밀국수를 먹을까?",
      "regionLabel": "서촌",
      "choices": {}
    },
    {
      "id": "bagel-tea",
      "region": "anguk",
      "category": "cafe",
      "placeIds": [
        "london",
        "chatteul"
      ],
      "title": "베이글을 고르거나, 차 한 잔에 머물거나",
      "reason": "베이글 구매와 한옥에서 전통차를 마시는 시간을 비교해요.",
      "notice": "차마시는뜰은 주거 골목 안에 있어요. 매장 시간과 별개로 관광 방문시간·현장 안내를 확인하세요.",
      "shortTitle": "베이글을 고르거나, 차 한 잔에 머물거나",
      "regionLabel": "안국",
      "choices": {}
    },
    {
      "id": "coffee-tea-hanok",
      "region": "anguk",
      "category": "cafe",
      "placeIds": [
        "onion",
        "osulloc"
      ],
      "title": "빵과 커피, 차와 디저트",
      "reason": "어니언의 빵·커피와 오설록의 차 메뉴를 비교해요.",
      "shortTitle": "빵과 커피, 차와 디저트",
      "regionLabel": "안국",
      "choices": {}
    },
    {
      "id": "roasted-blended",
      "region": "anguk",
      "category": "cafe",
      "placeIds": [
        "fritz",
        "teatherapy"
      ],
      "title": "로스팅 커피와 블렌딩 차",
      "reason": "원서동의 커피·빵과 윤보선길의 허브·과일차 중 골라요.",
      "shortTitle": "로스팅 커피와 블렌딩 차",
      "regionLabel": "안국",
      "choices": {}
    },
    {
      "id": "seochon-cafe",
      "region": "seochon",
      "category": "cafe",
      "placeIds": [
        "staffpicks",
        "daeo"
      ],
      "title": "테라스 카페, 오래된 서점 카페",
      "reason": "바깥 좌석의 풍경과 오래된 책·마당이 남은 공간을 비교해요.",
      "notice": "두 곳 모두 구매·좌석 이용 조건이 있어요. 대오서점은 일반 도서관이 아닙니다.",
      "shortTitle": "테라스 카페, 오래된 서점 카페",
      "regionLabel": "서촌",
      "choices": {}
    },
    {
      "id": "hanok-courtyards",
      "region": "anguk",
      "category": "rest",
      "placeIds": [
        "baeryeom",
        "baekinje"
      ],
      "title": "작은 한옥, 넓은 가옥의 마당",
      "reason": "배렴 가옥의 작은 공간과 백인제가옥의 정원·건축을 비교해요.",
      "notice": "관람 공간입니다. 피크닉·장시간 좌석 이용과 내부 출입은 현장 규칙을 따라주세요.",
      "shortTitle": "작은 한옥, 넓은 가옥의 마당",
      "regionLabel": "안국",
      "choices": {}
    },
    {
      "id": "park-hanok",
      "region": "seochon",
      "category": "rest",
      "placeIds": [
        "sajik",
        "sangchon"
      ],
      "title": "공원 길을 걷거나, 한옥을 둘러보거나",
      "reason": "사직공원의 야외 산책과 상촌재의 마당·온돌 관람을 비교해요.",
      "shortTitle": "공원 길을 걷거나, 한옥을 둘러보거나",
      "regionLabel": "서촌",
      "choices": {}
    },
    {
      "id": "hanok-life",
      "region": "anguk",
      "category": "culture",
      "placeIds": [
        "baekinje",
        "bukchoncenter"
      ],
      "title": "근대 한옥의 생활, 북촌의 한옥문화",
      "reason": "백인제가옥의 주거 구조와 북촌문화센터의 한옥·문화 안내를 비교해요.",
      "notice": "가옥 내부 해설과 문화센터 프로그램은 각각 예약·일정을 확인하세요.",
      "shortTitle": "근대 한옥의 생활, 북촌의 한옥문화",
      "regionLabel": "안국",
      "choices": {}
    },
    {
      "id": "museum-gallery",
      "region": "anguk",
      "category": "art",
      "placeIds": [
        "mmca",
        "hakgojae"
      ],
      "title": "여러 전시를 넓게, 갤러리 한 곳을 가깝게",
      "reason": "국립현대미술관의 여러 전시와 학고재의 현재 전시를 비교해요.",
      "shortTitle": "여러 전시를 넓게, 갤러리 한 곳을 가깝게",
      "regionLabel": "안국",
      "choices": {}
    },
    {
      "id": "artist-writer",
      "region": "seochon",
      "category": "art",
      "placeIds": [
        "park",
        "yisang"
      ],
      "title": "화가의 작품, 작가의 기록",
      "reason": "박노수미술관의 회화와 이상의 집의 문학 전시를 비교해요.",
      "shortTitle": "화가의 작품, 작가의 기록",
      "regionLabel": "서촌",
      "choices": {}
    },
    {
      "id": "seochon-art",
      "region": "seochon",
      "category": "art",
      "placeIds": [
        "daelim",
        "boan"
      ],
      "title": "기획전 미술관, 옛 여관의 예술공간",
      "reason": "대림미술관의 기획전과 보안1942의 건물·전시를 비교해요.",
      "notice": "전시 공백기에는 방문할 전시가 없을 수 있어요. 현재 전시와 요금을 먼저 확인하세요.",
      "shortTitle": "기획전 미술관, 옛 여관의 예술공간",
      "regionLabel": "서촌",
      "choices": {}
    },
    {
      "id": "knot-tea",
      "region": "anguk",
      "category": "make",
      "placeIds": [
        "donglim",
        "teatherapy"
      ],
      "title": "매듭으로 남길까, 차의 향으로 남길까?",
      "reason": "전통 매듭 만들기와 취향에 맞는 차·차 프로그램을 비교해요.",
      "notice": "공방·차 수업은 당일 참여를 보장하지 않아요. 예약·비용·언어·완성품 수령을 확인하세요.",
      "shortTitle": "매듭으로 남길까, 차의 향으로 남길까?",
      "regionLabel": "안국",
      "choices": {
        "teatherapy": {
          "visitWhen": "차를 고르거나 예약한 차 프로그램 참여",
          "useMode": "차·상품 구매 · 차 수업은 별도 예약·비용 확인"
        }
      }
    },
    {
      "id": "tea-coffee-gifts",
      "region": "anguk",
      "category": "make",
      "placeIds": [
        "osulloc",
        "fritz"
      ],
      "title": "차 선물, 커피 선물",
      "reason": "찻잎·차 상품과 원두·드립백을 비교해요. 카페 메뉴 가격과 상품 가격은 달라요.",
      "notice": "두 지점의 현재 상품·재고·포장과 가져갈 나라의 반입 조건을 확인하세요.",
      "shortTitle": "차 선물, 커피 선물",
      "regionLabel": "안국",
      "choices": {
        "osulloc": {
          "visitWhen": "찻잎·차 상품 고르기",
          "cost": "선물 상품별 유료 · 재고 확인",
          "useMode": "상품 구매 · 매장 재고·포장 확인"
        },
        "fritz": {
          "visitWhen": "원두·드립백 선물 고르기",
          "cost": "선물 상품별 유료 · 재고 확인",
          "useMode": "상품 구매 · 매장 재고·포장 확인"
        }
      }
    },
    {
      "id": "rain-royal-art",
      "region": "seochon",
      "category": "weather",
      "placeIds": [
        "gogung",
        "daelim"
      ],
      "title": "비 오는 서촌, 왕실 유물이나 기획전",
      "reason": "고궁박물관의 실내 전시와 대림미술관의 기획전을 비교해요.",
      "shortTitle": "비 오는 서촌, 왕실 유물이나 기획전",
      "regionLabel": "서촌",
      "choices": {}
    },
    {
      "id": "rain-reading-culture",
      "region": "anguk",
      "category": "weather",
      "placeIds": [
        "folk",
        "jeongdok"
      ],
      "title": "생활문화 전시, 조용한 자료실",
      "reason": "민속박물관의 일반 전시와 정독도서관 자료 열람을 비교해요.",
      "notice": "도서관은 조용히 이용하는 공간이에요. 좌석을 보장하지 않으며 건물까지의 이동은 야외입니다.",
      "shortTitle": "생활문화 전시, 조용한 자료실",
      "regionLabel": "안국",
      "choices": {}
    },
    {
      "id": "rain-artist-spaces",
      "region": "seochon",
      "category": "weather",
      "placeIds": [
        "park",
        "boan"
      ],
      "title": "작은 미술관에서 비를 피해 관람하기",
      "reason": "박노수미술관과 보안1942의 실내 전시를 비교해요.",
      "notice": "입구·정원·건물 간 이동에는 비를 맞을 수 있어요. 젖은 계단과 전시 운영 여부를 확인하세요.",
      "shortTitle": "작은 미술관에서 비를 피해 관람하기",
      "regionLabel": "서촌",
      "choices": {}
    },
    {
      "id": "family-royal",
      "region": "seochon",
      "category": "family",
      "placeIds": [
        "gyeongbok",
        "gogung"
      ],
      "title": "궁궐을 직접 걷거나, 왕실 물건을 보거나",
      "reason": "야외 건축 중심 경복궁과 실내 유물 중심 고궁박물관을 아이의 관심에 맞춰 골라요.",
      "notice": "어린이 전용 체험 예약이 포함된 비교는 아닙니다. 유모차 동선·가족 감면·교육 일정은 별도 확인하세요.",
      "shortTitle": "궁궐을 직접 걷거나, 왕실 물건을 보거나",
      "regionLabel": "서촌",
      "choices": {}
    },
    {
      "id": "family-break",
      "region": "seochon",
      "category": "family",
      "placeIds": [
        "tongin",
        "sajik"
      ],
      "title": "아이의 다음 쉼표, 간식일까 산책일까?",
      "reason": "시장에서 음식을 고르는 시간과 공원에서 걷는 시간을 비교해요.",
      "notice": "시장 통로·뜨거운 음식과 공원 경사에 주의하세요. 도시락 식사 공간의 유모차 접근은 먼저 확인하세요.",
      "shortTitle": "아이의 다음 쉼표, 간식일까 산책일까?",
      "regionLabel": "서촌",
      "choices": {}
    },
    {
      "id": "family-hanok",
      "region": "anguk",
      "category": "family",
      "placeIds": [
        "workshop",
        "baekinje"
      ],
      "title": "손으로 만들까, 한옥 구조를 살펴볼까?",
      "reason": "전통공예 만들기와 가옥·정원 관람을 비교해요.",
      "notice": "아이의 연령·작업 도구·보호자 조건은 체험별로 확인하세요. 백인제가옥 일부 실내는 해설 예약이 필요합니다.",
      "shortTitle": "손으로 만들까, 한옥 구조를 살펴볼까?",
      "regionLabel": "안국",
      "choices": {}
    },
    {
      "id": "free-craft-house",
      "region": "anguk",
      "category": "free",
      "placeIds": [
        "craft",
        "baekinje"
      ],
      "title": "관람료 없이 공예 전시나 한옥 보기",
      "reason": "공예박물관 일반 전시와 백인제가옥 일반 개방 구역을 비교해요.",
      "notice": "무료 관람에도 휴관일·예약 조건이 있습니다. 어린이관·특별 프로그램·상품은 별도 확인하세요.",
      "shortTitle": "관람료 없이 공예 전시나 한옥 보기",
      "regionLabel": "안국",
      "choices": {}
    },
    {
      "id": "free-life-hanok",
      "region": "anguk",
      "category": "free",
      "placeIds": [
        "folk",
        "bukchoncenter"
      ],
      "title": "생활문화 전시, 북촌의 한옥 구경",
      "reason": "민속박물관 일반 전시와 북촌문화센터 일반 공간을 비교해요.",
      "notice": "어린이관 예약과 문화센터의 유료·신청 프로그램은 무료 일반 관람과 다릅니다.",
      "shortTitle": "생활문화 전시, 북촌의 한옥 구경",
      "regionLabel": "안국",
      "choices": {
        "bukchoncenter": {
          "cost": "일반 공간 무료 · 프로그램 별도",
          "useMode": "일반 한옥 공간 관람 · 강좌·체험은 별도 신청",
          "checkUrl": "https://english.visitseoul.net/tours/Bukchon_/872"
        }
      }
    },
    {
      "id": "free-royal-ondol",
      "region": "seochon",
      "category": "free",
      "placeIds": [
        "gogung",
        "sangchon"
      ],
      "title": "왕실의 물건, 한옥의 온돌",
      "reason": "무료 일반 전시로 왕실 생활과 한옥 주거의 차이를 살펴요.",
      "shortTitle": "왕실의 물건, 한옥의 온돌",
      "regionLabel": "서촌",
      "choices": {}
    },
    {
      "id": "free-outdoor",
      "region": "seochon",
      "category": "free",
      "placeIds": [
        "sajik",
        "suseongdong"
      ],
      "title": "입장료 없이 공원이나 계곡 산책",
      "reason": "사직공원의 길과 수성동 계곡의 바위·산자락 풍경을 비교해요.",
      "notice": "무료여도 모든 구간이 평탄하거나 항상 열려 있지는 않아요. 기상·현장 통제를 확인하세요.",
      "shortTitle": "입장료 없이 공원이나 계곡 산책",
      "regionLabel": "서촌",
      "choices": {}
    }
  ]
};
  window.ALLEY_PLACES.push(...catalog.places);
  window.ALLEY_CATEGORIES = catalog.categories;
  // Preserve existing shared comparison IDs while giving exhibitions a clear home.
  window.BLIND_SPOT_PAIRS.find(pair => pair.id === 'baeryeom').category = 'art';
  window.BLIND_SPOT_PAIRS.push(...catalog.pairs);
  // The overview samples different purposes before showing second pairs.
  const categoryOrder = new Map(catalog.categories.map((category, index) => [category.id, index]));
  const withinCategory = new Map();
  const order = new Map(window.BLIND_SPOT_PAIRS.map(pair => {
    const rank = withinCategory.get(pair.category) || 0;
    withinCategory.set(pair.category, rank + 1);
    return [pair.id, rank * catalog.categories.length + categoryOrder.get(pair.category)];
  }));
  window.BLIND_SPOT_PAIRS.sort((a, b) => order.get(a.id) - order.get(b.id));
})();
